[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/my-roster-ics"
  to = "/.netlify/functions/my-roster-ics"
  status = 200

[[redirects]]
  from = "/my-roster-ics/*"
  to = "/.netlify/functions/my-roster-ics/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173

[[blob_stores]]
name = "acamed-roster"